sudo: false
language: python
python:
    - "3.6"
install:
  pip install -e .[dev]

jobs:
  include:
    - stage: test
      script: ./cover.sh
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: canary
      if: branch = canary
      script:
        - rm test/cassettes/*
        - ls test/cassettes/
        - ./cover.sh
    - stage: deploy
      if: branch = master
      script:
        - python d3is.py
        - mkdir dist
        - cp items.json dist/
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: dist
        github_token: $GITHUB_OAUTH_TOKEN
        on:
          branch: master
